Authentication/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AuthenticationApp.urls', namespace='authenticationApp'))

]

AuthenticationApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'authenticationApp'


urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('register/', views.registerPage, name='registerPage'),
    path('accounts/profile/', views.profilePage, name='profilePage'),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='app/logout.html'), name='logout'),

]

AuthenticationApp/models.py
from django.db import models

# Create your models here.

AuthenticationApp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .form import UserRegistrationforms


def homePage(request):

    return render(request, 'app/home.html', )


def registerPage(request):
    form = UserRegistrationforms()
    if request.method == "POST":
        form = UserRegistrationforms(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Hi {username} your account has been created successfully')

        else:
            form = UserRegistrationforms()
            messages.error(request,
                           ' Failed to create your account. Please check your details')

    return render(request, 'app/register.html', {'form': form})


def profilePage(request):
    return render(request, 'app/accounts/profile.html')

AuthenticationApp/templates/app/accounts/profile.html
<title>Profile</title>
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<div class="container p-3 my-3 bg-primary text-white">
  <h3>USERNAME: {{user.username}}</h3>
  <h3>EMAIL ADDRESS: {{user.email}}</h3>
</div>

AuthenticationApp/templates/app/base.html
{% block content%}


<title>Registration</title><!------>
<link
  href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.0.8/css/all.css"
/>

<div class="container">
  <br />
  <p>SIGN UP</p>
  <hr />

  <div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px">

      <form method="POST" action="">
                {% csrf_token %}
      
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
          </div>
          <input
            name="Username"
            class="form-control"
            placeholder="Username"
            type="text"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-envelope"></i>
            </span>
          </div>
          <input
            name="email"
            class="form-control"
            placeholder="Email address"
            type="email"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
          </div>

          <input
            name="telephone"
            class="form-control"
            placeholder="Phone number"
            type="text"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-building"></i>
            </span>
          </div>
          <select class="form-control">
            <option selected="">Select job type</option>
            <option value="Designer">Designer</option>
            <option value="Manager">Manager</option>
            <option value="Accounting">Accounting</option>
            <option value="Programmer">Programmer</option>
            <option value="Banker">Banker</option>
            <option value="Teacher">Teacher</option>
            <option value="Driver">Driver</option>
          </select>
        </div>
        <!-- form-group end.// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
          <input
          name="password"
            class="form-control"
            placeholder="Create password"
            type="password"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
          <input
           name="password"
            class="form-control"
            placeholder="Repeat password"
            type="password"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
            Create Account
          </button>
        </div>
        <!-- form-group// -->
        <p class="text-center">Already have an account? <a href="">Log In</a></p>
      </form>
    </article>
  </div>
  <!-- card.// -->
</div>
<!--container end.//-->
</form>

{% endblock %}

AuthenticationApp/templates/app/home.html
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Home</title>

    <!-- Favicons -->

    <style>
      body {
        background-image: url("https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/content/cover_image_file/cover_image/686299/cover-Redesign-WebSecurityVulnerabilities-Luke_Newsletter-04d5cdafdaf363f0bc6aa723a391c343-91ee4d294318c967b26187f4d67a8351.png");
      }
      button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16;
  margin: 20px;
 opacity: 0.9;
 border-radius: 2%;

 button:hover {opacity:1;}

    </style>

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet" />

     <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block" onclick="window.location.href='{% url 'authenticationApp:registerPage'%}'">
            Create Account
          </button>
           <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block" onclick="window.location.href='{% url 'authenticationApp:login'%}'">
           Login
          </button>

  </head>
  <body class="d-flex h-100 text-center text-white bg-dark"></body>
</html>

AuthenticationApp/templates/app/login.html
{% extends "app/base.html"%} {% load crispy_forms_tags %}
<h1>Login</h1>
<!--
<form method="POST" action="">
  {% csrf_token %} {{form|crispy}}

  <button type="submit" name="submit">Enter</button>
</form>
-->

{% block content%}
<link
  href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.0.8/css/all.css"
/>

<div class="container">
  <br />
  <p>   LOGIN</p>
  <hr />

  <div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px">

      <form method="POST" action="">
                {% csrf_token %}
      
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
          </div>
                    {{ form.username}}

        </div>
        <!-- form-group// -->
        
        <!-- form-group// -->
        
        <!-- form-group// -->
        
        <!-- form-group end.// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
                   {{ form.password}}

        </div>
        <!-- form-group// -->
        
        <!-- form-group// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
         LOGIN
          </button>
        </div>
        <!-- form-group// -->
        <p class="text-center">Don't have an account? <a href="{% url 'authenticationApp:registerPage'%}">Sign Up</a></p>
      </form>
    </article>
  </div>
  <!-- card.// -->
</div>
<!--container end.//-->
</form>


{% endblock%}
<div>
  {% if messages%} {% for message in messages%}
  <div class="alert" alert-{{message.tags}}>{{message}}</div>
  {% endfor %} {% endif %}
</div>

AuthenticationApp/templates/app/logout.html
<style>

       button {
   background-color: #4CAF50; /* Green */
   border: none;
   color: white;
   padding: 15px 32px;
   text-align: center;
   text-decoration: none;
   display: inline-block;
   font-size: 16;
   margin: 20px;
  opacity: 0.9;
  border-radius: 2%;

  button:hover {opacity:1;}
</style>

<div class="container p-3 my-3 bg-primary text-white">
  <h1>Logged out</h1>
</div>
<button
  type="submit"
  class="btn btn-primary btn-block"
  onclick="window.location.href='{% url 'authenticationApp:login'%}'"
>
  Login again
</button>

AuthenticationApp/templates/app/register.html
{% extends "app/base.html"%} {% load crispy_forms_tags %}
<!---->
<title>Register</title>
<!-->
<form method="POST" action="">
  {% csrf_token %} {{form|crispy}}

  <button type="submit" name="submit">Enter</button>
</form>
{% block content%} 
<!-->

<title>Registration</title><!---->
<link
  href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  rel="stylesheet"
  id="bootstrap-css"
/>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Include the above in your HEAD tag -->

<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.0.8/css/all.css"
/>

<div class="container">
  <br />
  <p>SIGN UP</p>
  <hr />

  <div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px">

      <form method="POST" action="">
                {% csrf_token %}
      
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
          </div>
          {{ form.username}}
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-envelope"></i>
            </span>
          </div>
         {{ form.email}}
        </div>
        <!-- form-group// -->
        
        <!-- form-group// -->
        
        <!-- form-group end.// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
                    {{ form.password1}}

        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
                    {{ form.password2}}

        </div>
        <!-- form-group// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
            Create Account
          </button>
        </div>
        <!-- form-group// -->
        <p class="text-center">Already have an account? <a href="{% url 'authenticationApp:login'%}">Log In</a></p>
      </form>
    </article>
  </div>
  <!-- card.// -->
</div>
<!--container end.//-->
</form>

<div>
  {% if messages%} {% for message in messages%}
  <div class="alert" alert-{{message.tags}}>{{message}}</div>
  {% endfor %} {% endif %}
</div>

{% endblock%}